# Generated by Django 3.2.4 on 2021-08-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='http://via.placeholder.com/640x360', max_length=500),
        ),
    ]
